Deprecate needsOrg & wantsOrg
heroku/cli-engine pull request #144
Opened 2017-05-18 17:30 UTC by RasPhilCo

2017-05-18 17:33 UTC, dickeyxxx commented
we'll need to wait until all the core plugins have moved over to the new flag to use this

2017-05-18 17:34 UTC, dickeyxxx commented
@dmcinnes as part of this, should we allow people to use `--org` in place of `--team` but hide the `--org` flag?

2017-05-25 01:06 UTC, jdx requested changes

2017-05-25 01:06 UTC, dickeyxxx commented on src/plugins/legacy.js
> +    new Output().warn(`--org in ${c.topic}${c.command ? ':' + c.command : ''} is deprecated`)
you should be able to use `this.out`. You should never create a new output because it won't reuse the existing config object if you do this

2017-05-30 22:56 UTC, dmcinnes commented
@dickeyxxx yeah that sounds right to me.

2017-05-30 22:57 UTC, dmcinnes commented
Whoops thought this was my PR 😅  In any case it's updated.

2017-10-06 18:04 UTC, RasPhilCo commented
@jdxcode Lol. PR is no good now, can't even see what the original change was. I'll address this is they whenever they tell us the deprecation warning should go live.

2017-10-06 18:04 UTC, closed without merging