WIP Add autocomplete
heroku/cli-engine pull request #172
Opened 2017-06-05 13:59 UTC by RasPhilCo

2017-06-07 22:48 UTC, RasPhilCo commented on src/commands/autocomplete.js
> +    const autocompletePath = path.join(this.config.dataDir, 'client', 'autocomplete')
@dickeyxxx I think I going to error here on brand new v6 installs b/c of the cli vs client dir thing we talked about earlier

2017-06-20 22:37 UTC, jdx requested changes

2017-06-20 22:37 UTC, dickeyxxx commented on src/commands/autocomplete.js
> +      this.out.warn('Autocomplete is not currently supported in Windows')
this is an error

2017-06-20 22:37 UTC, dickeyxxx commented on src/commands/update.js
> +        if (c.hidden) return
should filter this out instead of leaving nulls

2017-06-20 22:37 UTC, dickeyxxx commented on src/commands/update.js
> +        let plublicFlags = Object.keys(c.flags).filter(flag => !c.flags[flag].hidden).map(flag => `--${flag}`).join(' ')
typo

2017-06-20 22:37 UTC, dickeyxxx commented on src/commands/autocomplete.js
> +        this.out.log(CustomColors.cmd(`$ ln -s ${fnFile} /usr/local/etc/bash_completion.d/heroku`))
I'd love it if we had a way to verify bash is actually picking this up, but I'm not sure we can

2017-06-20 22:37 UTC, dickeyxxx commented on src/commands/autocomplete.js
> +        this.out.log(`Currently ${shell} not a supported shell for autocomplete`)
this is an error right?

2017-06-20 22:37 UTC, dickeyxxx commented on src/commands/autocomplete.js
> +    let shell = this.flags.shell
could do `const shell = this.flags.shell || this.config.shell`

2017-06-20 22:37 UTC, dickeyxxx commented on src/commands/update.js
> +import flatten from 'lodash.flatten'
could lazy-load this one

2017-06-20 22:37 UTC, dickeyxxx commented on src/commands/update.js
> +      fs.mkdirpSync(path.join(this.config.dataDir, 'client', 'autocomplete'))
prefer `await fs.mkdirp()` and `await fs.writeFile()`

good to get in the habit of using async when we can

2017-06-20 22:44 UTC, dickeyxxx commented on src/commands/autocomplete.js
> +  async run () {
can you write a test to at least execute this code? Seeing a lot of red from codecov right now

2017-06-20 23:20 UTC, dickeyxxx commented on src/commands/autocomplete.test.js
> +  if (os.platform() === 'windows') return
hmm maybe we could do this better...

```js
let skipWindows = os.platform() === 'windows' ? xtest : test
skipWindows('outputs commands file path', async () => {
```

2017-06-20 23:55 UTC, dickeyxxx commented on src/commands/autocomplete.js
> +    const autocompletePath = path.join(this.config.dataDir, 'client', 'node_modules', 'cli-engine', 'autocomplete')
```js
const autocompletePath = path.join(__dirname, '..', '..', 'autocomplete')
```

2017-06-20 23:57 UTC, dickeyxxx commented on src/commands/update.js
> +      fs.writeFileSync(path.join(this.config.dataDir, 'client', 'node_modules', 'cli-engine', 'autocomplete', 'commands'), commands)
`await fs.outputFile()`

2017-06-21 00:14 UTC, jdx approved these changes

2017-06-21 13:59 UTC, merged