Convert v5 cmds to v6 for completions
heroku/cli-engine pull request #224
Opened 2017-06-29 18:17 UTC by RasPhilCo

2017-06-29 21:50 UTC, dickeyxxx commented on src/commands/autocomplete/script.js
> +        const c = typeof Command === 'function' ? Command : convertFromV5((Command: any))
I feel that this file should not have to be aware of v5 commands. Can you instead make a helper inside of `plugins/index.js` to export all the commands already converted to v6?

2017-06-29 21:50 UTC, RasPhilCo commented on src/commands/autocomplete/script.js
> +        const c = typeof Command === 'function' ? Command : convertFromV5((Command: any))
this is wrong, waiting update

2017-06-29 22:01 UTC, RasPhilCo commented on src/commands/autocomplete/script.js
> +        if (c.args && c.args.find(a => a.name === 'app')) publicFlags.concat(' --app')
Thoughts? This is the cached plugin so no idea if it's needsApp/wantsApp, thus no idea if it's *actually* supporting the app flag.

2017-06-30 02:56 UTC, dickeyxxx commented on src/commands/autocomplete/script.js
> +        if (c.args && c.args.find(a => a.name === 'app')) publicFlags.concat(' --app')
I don't understand. If it takes an app as an arg you add the app flag? Is this supposed to add functionality for args as flags?

2017-06-30 15:23 UTC, RasPhilCo commented on src/commands/autocomplete/script.js
> +        if (c.args && c.args.find(a => a.name === 'app')) publicFlags.concat(' --app')
@garyposter Mentioned some commands that he didn't see have app flags in completion, namely needsApp/wantsApp commands. This is hack to solve that but probably introduces another problem.

2017-06-30 15:25 UTC, RasPhilCo commented on src/commands/autocomplete/script.js
> +        if (c.args && c.args.find(a => a.name === 'app')) publicFlags.concat(' --app')
```
        {
          "id": "apps:info",
          "topic": "apps",
          "command": "info",
          "description": "show detailed app information",
          "args": [
            {
              "name": "app",
              "hidden": true,
              "optional": true
            }
          ],
          "help": "Examples:\n\n $ heroku apps:info\n === example\n Git URL:   https://git.heroku.com/example.git\n Repo Size: 5M\n ...\n\n $ heroku apps:info --shell\n git_url=https://git.heroku.com/example.git\n repo_size=5000000\n ...",
          "hidden": false,
          "aliases": [],
          "flags": {
            "shell": {
              "char": "s",
              "description": "output more shell friendly key/value pairs"
            },
            "extended": {
              "char": "x",
              "hidden": true
            },
            "json": {
              "char": "j"
            }
          }
```

2017-06-30 15:25 UTC, RasPhilCo commented on src/commands/autocomplete/script.js
> +        if (c.args && c.args.find(a => a.name === 'app')) publicFlags.concat(' --app')
Should we add needsApp/wantsApp app flag to cache? That would solve it for me but...

2017-06-30 16:12 UTC, dickeyxxx commented on src/commands/autocomplete/script.js
> +        if (c.args && c.args.find(a => a.name === 'app')) publicFlags.concat(' --app')
I think you'll need to rehydrate each command rather than just using the cache. Or dynamically generate the flags somehow.

2017-07-05 21:45 UTC, RasPhilCo commented
@dickeyxxx updated to rehydrate plugins. `--app` and `--remote` now appears from legacy conversion.

2017-07-06 17:51 UTC, RasPhilCo commented on src/commands/autocomplete/script.js
> +      fs.writeFileSync(path.join((new this().completionsPath), 'commands'), commands)
Let me know if this makes you haz sad

2017-07-06 18:24 UTC, dickeyxxx commented on src/commands/autocomplete/script.js
> +      fs.writeFileSync(path.join((new this().completionsPath), 'commands'), commands)
I don't understand, why can't you just do `this.completionsPath`?

2017-07-06 18:25 UTC, jdx requested changes

2017-07-06 18:25 UTC, dickeyxxx commented on src/commands/autocomplete/script.js
> +      fs.writeFileSync(path.join((new this().completionsPath), 'commands'), commands)
oh because it's static. Why is it static? This is a terrible idea, you lose the config object this way

2017-07-06 19:51 UTC, RasPhilCo commented
moving scripting to a helper class cause i need to extended it soon anyhow

2017-07-19 23:39 UTC, jdx approved these changes

2017-07-19 23:40 UTC, merged