hide topic cmds help if only 1 cmd
heroku/cli-engine pull request #251
Opened 2017-07-31 20:38 UTC by RasPhilCo

closes https://github.com/heroku/cli/issues/513

2017-07-31 20:41 UTC, jdx approved these changes

2017-07-31 20:42 UTC, jdx requested changes
it's possible that there is 1 command but it isn't a root command. In which case we would need to show the index.

2017-08-01 16:58 UTC, RasPhilCo commented
@dickeyxxx i'm checking for matchedCommand presence inside of `if topic`, so if they are both present it can only be a topic-command

2017-08-01 17:20 UTC, jdx approved these changes

2017-08-01 17:20 UTC, dickeyxxx commented
ah I see now, looks good!

2017-08-01 23:48 UTC, merged