add plugins:parse hook in require
heroku/cli-engine pull request #287
Opened 2017-09-19 13:16 UTC by RasPhilCo

2017-09-19 15:50 UTC, jdx requested changes

2017-09-19 15:50 UTC, jdxcode commented on src/plugins/manager.js
> +      required = await hooks.run('plugins:parse', {module: require(this.path)}) || require(this.path)
I don't understand this conditional, it'll never be hit right?

2017-09-19 17:59 UTC, jdxcode commented
ignore the appveyor issue, it's unrelated. I'll have to fix that post-shinzi

2017-09-26 16:22 UTC, rbergman approved these changes

2017-09-26 16:26 UTC, merged